import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nanum_Gothic } from "next/font/google";
import "../css/tailwind.css";
import Header from "../components/Header";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import localFont from "next/font/local";
import BaseLayout from "./../layouts/BaseLayout";

const inter = Inter({ subsets: ["latin"] });

const nanum_gothic = Nanum_Gothic({
  weight: ["400", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LOL.FIGHT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-['Pretendard'] bg-brandbgcolor">
      <body>
        <BaseLayout>{children}</BaseLayout>
      </body>
      {/* <body className={`${pretendard.className}`}>{children}</body> */}
    </html>
  );
}
